export const environment = {
  production: true,
  baseURL: 'https://api.fit-meetups.ru',
  LS_API_KEY: 'my-secret-key',
  apiKey: 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImppbUBkdW5kZXJtaWZmbGluLmNvbSIsImlkIjoxMzksInJvbGVzIjpbeyJpZCI6MiwibmFtZSI6IlVTRVIiLCJjcmVhdGVkQXQiOiIyMDAyLTAxLTAxVDAwOjAwOjAwLjAwMFoiLCJ1cGRhdGVkQXQiOiIyMDAyLTAxLTAxVDAwOjAwOjAwLjAwMFoiLCJVc2VyUm9sZSI6eyJpZCI6MjAxLCJ1c2VySWQiOjEzOSwicm9sZUlkIjoyLCJjcmVhdGVkQXQiOiIyMDIyLTEyLTIwVDIxOjA1OjU3LjI2NloiLCJ1cGRhdGVkQXQiOiIyMDIyLTEyLTIwVDIxOjA1OjU3LjI2NloifX1dLCJpYXQiOjE2ODc1MzQxNTMsImV4cCI6MTY4NzYyMDU1M30.fwKyYtnOrii6blVxe8kGVkHVWv1cnrp37s9QTp75ev0'
};
